# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c988ec1852de3b0723e5cad1038990d1a27087ab889063951ff45e087b766ca776b0c966cab27427e0c8d71b60a035989b3855382d4a926a2871570456f35281

test:
  secret_key_base: 85e076a805dbf325d8aa357be831d5e1c5d4d4a1cd37a9822e08029f327b68986eba3fc4a2973c0c896a9198f687b6b0a812de3b39788e152daa122be7b318dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
